force-app/main/default/objects/ErrorEvent__e/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <defaultValue>&quot;Salesforce exception&quot;</defaultValue>
    <label>Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorEvent__e/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <description>The Id for the error</description>
    <label>Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorEvent__e/fields/TotalErrors__c.field-meta.xml
<CustomField>
    <fullName>TotalErrors__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Total Errors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c.object
<CustomObject>
    <fields>
        <fullName>ErrorSubtype__c</fullName>
        <label>Error Sub-type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Undefined</fullName>
                    <default>true</default>
                    <label>Undefined</label>
                </value>
                <value>
                    <fullName>System.DmlException</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ErrorType__c</fullName>
        <label>Error Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HttpResponse__e/HttpResponse__e.object-meta.xml
<CustomObject>
    <label>Http Response</label>
    <pluralLabel>Http Responses</pluralLabel>
</CustomObject>

force-app/main/default/objects/HttpResponse__e/fields/EndpointSetting__c.field-meta.xml
<CustomField>
    <fullName>EndpointSetting__c</fullName>
    <description>The qualified API name of the Endpoint settings</description>
    <label>Endpoint Setting</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HttpResponse__e/fields/IsSuccess__c.field-meta.xml
<CustomField>
    <fullName>IsSuccess__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A boolean identifier for whether the callout was successful</description>
    <label>Success</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HttpResponse__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The results of HttpResponse.getStatus()</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HttpResponse__e/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>The results of HttpResponse.getStatusCode()</description>
    <label>Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventProcessing.cls
/**
* @author Addepar
* @date 2022
* @group Event Bus
* @description Methods to publish platform events
*/
public with sharing class EventProcessing {
    
    public static void publishHttpResponseEvent(HttpResponse response,String epsQualifiedAPIName){
        AccessControls controls = AccessControls.getSObjectAccessControls(SObjectUtility.getSObjectForName('HttpResponse__e'));
        if(controls.invalidRequest || !controls.sObjectAccess.isCreateable){
            throwNoAccessException('HttpResponse__e');
        }else{
            HttpResponse__e results = new HttpResponse__e();
            results.Status__c = response.getStatus();
            results.StatusCode__c = String.valueOf(response.getStatusCode());
            results.IsSuccess__c = response.getStatusCode() == 200 ? true : false;
            results.EndpointSetting__c = epsQualifiedAPIName.indexOf('_') != -1 ? epsQualifiedAPIName.replaceAll('_',' ') : epsQualifiedAPIName;
            handleSaveResult(EventBus.publish(results),'HttpResponse__e');
        }
    }

    public static void publishErrorEvent(List<ErrorLog__c> newList){
        AccessControls controls = AccessControls.getSObjectAccessControls(SObjectUtility.getSObjectForName('ErrorEvent__e'));
        if(newList.isEmpty() || controls.invalidRequest || !controls.sObjectAccess.isCreateable){
            throwNoAccessException('ErrorEvent__e');
        }else if(newList.size() == 1){
           handleSaveResult(EventBus.publish(constructErrorEvent(newList[0],1,null)),'ErrorEvent__e'); 
        }else{
            String msg = 'Many errors occurred.  Category and Type reported are for the first error.  Please review Error Logs';
            handleSaveResult(EventBus.publish(constructErrorEvent(newList[0],newList.size(),msg)),'ErrorEvent__e');
        }
    }

    private static ErrorEvent__e constructErrorEvent(ErrorLog__c error,Integer totalErrors,String errorMessage){
        ErrorEvent__e evt = new ErrorEvent__e();
        evt.Id__c = error.Id;
        evt.Message__c = null == errorMessage ? error.Message__c : errorMessage;
        evt.TotalErrors__c = totalErrors;
        evt.Category__c = error.ErrorType__c;
        evt.Type__c = error.ErrorSubtype__c;
        return evt;
    }

    private static void throwNoAccessException(String eventName){
        LoggingHandler.debugException(new EventProcessingException('Invalid request or No access to event type'), StaticResources.EVENT_BUS_EXCEPTION, eventName);
        LoggingHandler.popAll();
    }


    private static void handleSaveResult(Database.SaveResult saveResult,String eventName){
        if(!saveResult.isSuccess()){
            String msgBody = '';
            for(Database.Error err : saveResult.getErrors()){
                msgBody = msgBody + err.getMessage() + '\n';
            }
            LoggingHandler.debugException(new EventProcessingException(msgBody), StaticResources.EVENT_BUS_EXCEPTION, eventName);
            LoggingHandler.popAll();
        }
    }

    public class EventProcessingException extends Exception{}
}