force-app/main/default/objects/ErrorLog__c.object
<CustomObject>
    <fields>
        <fullName>Duplicate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies this record for purge</description>
        <inlineHelpText>Set to true to have this record deleted during batch processing</inlineHelpText>
        <label>Duplicate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ErrorStackTrace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ErrorLogBeforeUpdateTriggerHandlerTest.cls
/**
* @author Kevin Winn
* @date 12/31/2019
* @group Test Classes
* @description before update trigger handler test for object 
*/
@isTest 
private class ErrorLogBeforeUpdateTriggerHandlerTest 
{
	@testSetup
	static void setupTestData()
	{
		TestDataFactory.generateErrorLogs(StaticResources.TEST_LIST_SIZE);
	}

	static testMethod void updateTestSuccess() 
	{
		Map<Id,ErrorLog__c> logs = new Map<Id,ErrorLog__c>(ErrorLogHelper.getErrorLogs());
		for(ErrorLog__c l : logs.values())
		{
			if(l.Duplicate__c == true)
			{
				l.Duplicate__c = false;
			}
		}
		Test.startTest();
		GlobalDMLHandler.updateObjectList(logs.values());
		Test.stopTest();

		List<ErrorLog__c> dupes = [Select Id From ErrorLog__c Where Duplicate__c = true];
		System.assertNotEquals(true,dupes.isEmpty(),'dupes are empty');
	}

	static testMethod void testFieldUpdateDupeCheck()
	{
		Map<Id,ErrorLog__c> logs = new Map<Id,ErrorLog__c>(ErrorLogHelper.getErrorLogs());
		for(ErrorLog__c l : logs.values())
		{
			l.ErrorStackTrace__c = '';
		}
		Test.startTest();
		GlobalDMLHandler.updateObjectList(logs.values());
		Test.stopTest();

		List<ErrorLog__c> uLogs = [Select Id From ErrorLog__c Where Duplicate__c = true];
		System.assertEquals(logs.size(),uLogs.size(),'log size mismatch');
	}
}