force-app/main/default/objects/ErrorLog__c.object
<CustomObject>
    <fields>
        <fullName>Duplicate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies this record for purge</description>
        <inlineHelpText>Set to true to have this record deleted during batch processing</inlineHelpText>
        <label>Duplicate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ErrorStackTrace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ErrorLogBeforeInsertTriggerHandler.cls
/**
* @author Kevin Winn
* @date May 17, 2022
* @group Trigger Handlers
* @description before insert trigger handler for object 
*/
public with sharing class ErrorLogBeforeInsertTriggerHandler extends TriggerHandlerBase {
	public override void mainEntry(TriggerParameters tp) {
		process((List<ErrorLog__c>)tp.newList);
	}

	private void process(List<ErrorLog__c> newList)	{
		for(ErrorLog__c l : newList){
			if(null == l.ErrorStackTrace__c || l.ErrorStackTrace__c.length() < 1){
				l.Duplicate__c = true;
			}
		}
	}
}