force-app/main/default/objects/ErrorLog__c.object
<CustomObject>
    <fields>
        <fullName>Duplicate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies this record for purge</description>
        <inlineHelpText>Set to true to have this record deleted during batch processing</inlineHelpText>
        <label>Duplicate</label>
        <type>Checkbox</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ErrorLogBeforeDeleteTriggerHandlerTest.cls
/**
* @author Kevin Winn
* @date 12/31/2019
* @group Test Classes
* @description before delete trigger handler test for object 
*/
@isTest 
private class ErrorLogBeforeDeleteTriggerHandlerTest 
{
	@testSetup
	static void setupTestData()
	{
		TestDataFactory.generateErrorLogs(StaticResources.TEST_LIST_SIZE);
	}

	static testMethod void deleteTestSuccess() 
	{
		Map<Id,ErrorLog__c> logs = new Map<Id,ErrorLog__c>(ErrorLogHelper.getErrorLogs());
		List<ErrorLog__c> dupes = new LIst<ErrorLog__c>();
		for(ErrorLog__c l : logs.values())
		{
			if(l.Duplicate__c == true)
			{
				dupes.add(l);
			}
		}
		Test.startTest();
		GlobalDMLHandler.deleteObjectList(dupes);
		Test.stopTest();

		List<ErrorLog__c> noDupes = [Select Id From ErrorLog__c Where Duplicate__c = false];
		System.assertNotEquals(true, noDupes.isEmpty(),'dupes are not empty');
	}

	static testMethod void deleteAgedLogsSuccess()
	{
		Integer target = -5;
		Test.startTest();
		ErrorLogHelper.deleteAgedErrorLogs(target);
		Test.stopTest();
		List<ErrorLog__c> logs = [Select Id From ErrorLog__c];
		System.assertEquals(true,logs.isEmpty(),'logs are not empty');
	}
}