force-app/main/default/objects/ErrorLog__c.object
<CustomObject>
    <fields>
        <fullName>Duplicate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies this record for purge</description>
        <inlineHelpText>Set to true to have this record deleted during batch processing</inlineHelpText>
        <label>Duplicate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ErrorStackTrace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ErrorType__c</fullName>
        <label>Error Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ErrorLogHelper.cls
/**
* @author Kevin Winn
* @date 01/01/2020
* @group Error Log
* @description helper class for ErrorLog__c handling
*/
public with sharing class ErrorLogHelper 
{
	/** 
	* @author Kevin Winn
	* @date 01/01/2020
	* @description get all error records that have not been deleted
	*/
	@auraEnabled
	public static List<ErrorLog__c> getErrorLogs()
	{
		List<ErrorLog__c> logs = new List<ErrorLog__c>();
		for(List<ErrorLog__c> records : [Select Id, Name, Object__c, ErrorType__c, ErrorStackTrace__c, CreatedDate,Duplicate__c 
											From ErrorLog__c 
											Where IsDeleted = false
											Order By CreatedDate])
		{
			if(!records.isEmpty())
			{
				logs.addAll(records);
			}
		}
		return logs;
	}

	/** 
	* @author Kevin Winn
	* @date 01/01/2020
	* @description get a map of count of errors by type name
	*
	@auraEnabled
	public static Map<String,Integer> getAggResultsByErrorType()
	{
		Map<String,Integer> aggMap = new Map<String,Integer>();
		for(List<AggregateResult> aggs : [Select ErrorType__c, COUNT(Id) qty
										From ErrorLog__c
										Group By ErrorType__c])
		{
			if(!aggs.isEmpty())
			{
				for(AggregateResult ar : aggs)
				{
					aggMap.put(String.valueOf(ar.get('ErrorType__c')),Integer.valueOf(ar.get('qty')));
				}
			}
			else{
				aggMap.put('No Errors',0);
			}	
		}
		return aggMap;
	}

	/** 
	* @author Kevin Winn
	* @date 01/01/2020
	* @description get a map of count of errors by Object name
	*
	@auraEnabled
	public static Map<String,Integer> getAggResultsByObjectType()
	{
		Map<String,Integer> aggMap = new Map<String,Integer>();
		for(List<AggregateResult> aggs : [Select Object__c, COUNT(Id) qty
										From ErrorLog__c
										Group By Object__c])
		{
			if(!aggs.isEmpty())
			{
				for(AggregateResult ar : aggs)
				{
					aggMap.put(String.valueOf(ar.get('Object__c')),Integer.valueOf(ar.get('qty')));
				}
			}
			else{
				aggMap.put('No Errors',0);
			}	
		}
		return aggMap;
	}

	/** 
	* @author Kevin Winn
	* @date 01/01/2020
	* @description get a map of count of errors by Created Date
	*
	@auraEnabled
	public static Map<Datetime,Integer> getAggResultsByCreatedDate()
	{
		Map<Datetime,Integer> aggMap = new Map<Datetime,Integer>();
		for(List<AggregateResult> aggs : [Select CreatedDate, COUNT(Id) qty
										From ErrorLog__c
										Group By CreatedDate])
		{
			if(!aggs.isEmpty())
			{
				for(AggregateResult ar : aggs)
				{
					aggMap.put(DateTime.valueOf(ar.get('CreatedDate')),Integer.valueOf(ar.get('qty')));
				}
			}
			else{
				aggMap.put(DateTime.now(),0);
			}	
		}
		return aggMap;
	}

	/** 
	* @author Kevin Winn
	* @date 01/01/2020
	* @description get a map of count of errors by type name filtered for one object
	* @param objectApiName the SObject API name to filter aggregate results by
	*
	@auraEnabled
	public static Map<String,Integer> getObjectAggResultsByErrorType(String objectApiName)
	{
		Map<String,Integer> aggMap = new Map<String,Integer>();
		for(List<AggregateResult> aggs : [Select ErrorType__c, COUNT(Id) qty
										From ErrorLog__c
										Where Object__c =: objectApiName
										Group By ErrorType__c])
		{
			if(!aggs.isEmpty())
			{
				for(AggregateResult ar : aggs)
				{
					aggMap.put(String.valueOf(ar.get('ErrorType__c')),Integer.valueOf(ar.get('qty')));
				}
			}
			else{
				aggMap.put('No Errors',0);
			}
		}
		return aggMap;
	}

	/** 
	* @author Kevin Winn
	* @date 01/01/2020
	* @description get a map of count of errors by Created Date filtered for one object
	* @param objectApiName the SObject API name to filter aggregate results by
	*
	@auraEnabled
	public static Map<Datetime,Integer> getObjectAggResultsByCreatedDate(String objectApiName)
	{
		Map<Datetime,Integer> aggMap = new Map<Datetime,Integer>();
		for(List<AggregateResult> aggs : [Select CreatedDate, COUNT(Id) qty
										From ErrorLog__c
										Where Object__c =: objectApiName
										Group By CreatedDate])
		{
			if(!aggs.isEmpty())
			{
				for(AggregateResult ar : aggs)
				{
					aggMap.put(DateTime.valueOf(ar.get('CreatedDate')),Integer.valueOf(ar.get('qty')));
				}
			}
			else{
				aggMap.put(DateTime.now(),0);
			}	
		}
		return aggMap;
	}

	/** 
	* @author Kevin Winn
	* @date 01/01/2020
	* @description get a map of count of errors by Created Date filtered for one object
	* @param objectApiName the SObject API name to filter aggregate results by
	*
	@auraEnabled
	public static List<ErrorLog__c> getErrorsByObject(String selectedObject)
	{
		return new List<ErrorLog__c>();
	}
*/
	public static void deleteAgedErrorLogs(Integer ageInDays)
	{
		Date age = (ageInDays < 0) ? Date.today() - ageInDays : (Date.Today() + (-1 * ageInDays));
		for(List<ErrorLog__c> records : [Select Id From ErrorLog__c WHere CreatedDate <= : age])
		{
			if(!records.isEmpty())
			{
				GlobalDMLHandler.deleteObjectList(records);
			}
		}
	}
}