force-app/main/default/objects/ErrorLog__c.object
<CustomObject>
    <fields>
        <fullName>Duplicate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies this record for purge</description>
        <inlineHelpText>Set to true to have this record deleted during batch processing</inlineHelpText>
        <label>Duplicate</label>
        <type>Checkbox</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ErrorLogAfterUpdateTriggerHandlerTest.cls
/**
* @author Kevin Winn
* @date 12/31/2019
* @group Test Classes
* @description after update trigger handler test for object 
*/
@isTest 
private class ErrorLogAfterUpdateTriggerHandlerTest 
{
	@testSetup
	static void setupTestData()
	{
		TestDataFactory.generateErrorLogs(StaticResources.TEST_LIST_SIZE);
	}

	static testMethod void updateTestSuccess() 
	{
		Map<Id,ErrorLog__c> logs = new Map<Id,ErrorLog__c>(ErrorLogHelper.getErrorLogs());
		Test.startTest();
		for(ErrorLog__c l : logs.values())
		{
			l.Duplicate__c = true;
		}
		GlobalDMLHandler.updateObjectList(logs.values());
		Test.stopTest();

		Map<Id,ErrorLog__c> updatedLogs = new Map<Id,ErrorLog__c>(ErrorLogHelper.getErrorLogs());
		System.assertEquals(logs.size(), updatedLogs.size(),'Log sizes do not match');
	}
}