force-app/main/default/objects/ErrorLog__c.object
<CustomObject>
    <fields>
        <fullName>Cause__c</fullName>
        <label>Cause</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DMLFieldNames__c</fullName>
        <label>DML Field Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duplicate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies this record for purge</description>
        <inlineHelpText>Set to true to have this record deleted during batch processing</inlineHelpText>
        <label>Duplicate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ErrorStackTrace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ErrorType__c</fullName>
        <label>Error Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
                <value>
                    <fullName>Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
                <value>
                    <fullName>Order</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ErrorLogBeforeInsertTriggerHandlerTest.cls
/**
* @author Kevin Winn
* @date 12/31/2019
* @group Test Classes
* @description before insert trigger handler test for object 
*/
@isTest 
private class ErrorLogBeforeInsertTriggerHandlerTest 
{

	static testMethod void insertTestSuccess() 
	{
		List<ErrorLog__c> logs = new List<ErrorLog__c>();
		for(Integer i = 0; i < 50; i++)
		{
			ErrorLog__c l = new ErrorLog__c();
			l.Cause__c = 'Test Cause';
			l.DMLFieldNames__c = 'Field1,Field2';
			l.ErrorStackTrace__c = 'ErrorStackTrace';
			l.ErrorType__c = 'Salesforce';
			l.Object__c = 'ErrorLog__c';
			logs.add(l);
		}

		Test.startTest();
		GlobalDMLHandler.insertObjectList(logs);
		Test.stopTest();

		List<ErrorLog__c> newLogs = [Select Id From ErrorLog__c Where IsDeleted = false];
		System.assertEquals(50,newLogs.size(),'Unexpected record count.  Expected 50');
	}

	static testMethod void testDuplicateEntryIdentification()
	{
		Test.startTest();
		TestDataFactory.generateErrorLogs(StaticResources.TEST_LIST_SIZE);
		Test.stopTest();

		List<ErrorLog__c> dupes = [Select Id From ErrorLog__c];
		List<ErrorLog__c> dupeId = [Select Id From ErrorLog__c Where Duplicate__c = true];
		System.assertEquals((dupes.size()/2),dupeId.size(),'dupe identification failed');
	}

	static testMethod void testSingleInsert()
	{
		Test.startTest();
		Map<id,ErrorLog__c> log = TestDataFactory.createErrorLogs(1, 'Account', 'Salesforce Exception', 'Undefined', null);
		Test.stopTest();
		System.assert(!log.isEmpty(),'Logs are empty');
	}
}