force-app/main/default/objects/ConnectionSetting__mdt/ConnectionSetting__mdt.object-meta.xml
<CustomObject>
    <description>Base URLs and other settings for API Connections</description>
    <label>Connection Setting</label>
    <pluralLabel>Connection Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConnectionSetting__mdt/fields/APIKey__c.field-meta.xml
<CustomField>
    <fullName>APIKey__c</fullName>
    <description>The API Key to connect to this endpoint</description>
    <inlineHelpText>The API Key to connect to this endpoint</inlineHelpText>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectionSetting__mdt/fields/APISecret__c.field-meta.xml
<CustomField>
    <fullName>APISecret__c</fullName>
    <inlineHelpText>The API Secret to connect to this endpoint</inlineHelpText>
    <label>API Secret</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConnectionSetting__mdt/fields/FirmId__c.field-meta.xml
<CustomField>
    <fullName>FirmId__c</fullName>
    <label>Firm Id</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EndpointSetting__mdt/EndpointSetting__mdt.object-meta.xml
<CustomObject>
    <description>Settings for a specific endpoint</description>
    <label>Endpoint Setting</label>
    <pluralLabel>Endpoint Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/EndpointSetting__mdt/fields/ConnectionSetting__c.field-meta.xml
<CustomField>
    <fullName>ConnectionSetting__c</fullName>
    <inlineHelpText>The connection setting for this endpoint</inlineHelpText>
    <label>Connection Setting</label>
    <referenceTo>ConnectionSetting__mdt</referenceTo>
    <relationshipLabel>Endpoint Settings</relationshipLabel>
    <relationshipName>EndpointSettings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/EndpointSetting__mdt/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <defaultValue>&quot;NOT_REQUIRED&quot;</defaultValue>
    <label>Content Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT_REQUIRED</fullName>
                <default>true</default>
                <label>NOT_REQUIRED</label>
            </value>
            <value>
                <fullName>application/vnd.api+json</fullName>
            </value>
            <value>
                <fullName>application/json</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HttpHeaders.cls
/**
* @author Addepar
* @date 2022
* @group API
* @description contains methods to construct the appropriate headers for an endpoint
* 
*/
public with sharing class HttpHeaders {

    public static final String NOT_REQUIRED = 'NOT_REQUIRED';
    
    public static HttpRequest buildAddeparHeaders(HttpRequest request,String epsQualifiedAPIName){
        EndpointSetting__mdt eps = new EndpointSettings().getEndpointSetting(epsQualifiedAPIName);
        ConnectionSetting__mdt connection = new EndpointSettings().getConnectionSetting(eps.ConnectionSetting__r.QualifiedAPIName);
        if(null == eps.QualifiedAPIName || eps.QualifiedAPIName != epsQualifiedAPIName){
            //TO DO:  Implement exception handling
        }else{
            
            request.setHeader('Addepar-Firm',String.valueOf(connection.FirmId__c));
            request.setHeader('Authorization','Basic ' + buildAuthVal(connection));
            if(eps.ContentType__c != NOT_REQUIRED){
                request.setHeader('Content-Type',eps.ContentType__c);
            }
        }
        return request;
    }

    public static HttpRequest buildFigiHeaders(HttpRequest request){
        return request;
    }

    private static String buildAuthVal(ConnectionSetting__mdt connection){
        String authVal = String.valueOf(connection.APIKey__c + ':' + connection.APISecret__c);
        authVal = EncodingUtil.base64Encode(blob.valueOf(authVal));
        return authVal;
    }
}