force-app/main/default/objects/ConnectionSetting__mdt/ConnectionSetting__mdt.object-meta.xml
<CustomObject>
    <description>Base URLs and other settings for API Connections</description>
    <label>Connection Setting</label>
    <pluralLabel>Connection Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConnectionSetting__mdt/fields/APIVersion__c.field-meta.xml
<CustomField>
    <fullName>APIVersion__c</fullName>
    <defaultValue>&quot;NA&quot;</defaultValue>
    <description>The API Version for this endpoint.  Leave as NA if no version is required in callout</description>
    <inlineHelpText>The API Version for this endpoint.  Leave as NA if no version is required in callout</inlineHelpText>
    <label>API Version</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NA</fullName>
                <default>true</default>
                <label>NA</label>
            </value>
            <value>
                <fullName>v1</fullName>
            </value>
            <value>
                <fullName>v2</fullName>
            </value>
            <value>
                <fullName>v3</fullName>
            </value>
            <value>
                <fullName>v4</fullName>
            </value>
            <value>
                <fullName>v5</fullName>
            </value>
            <value>
                <fullName>v6</fullName>
            </value>
            <value>
                <fullName>v7</fullName>
            </value>
            <value>
                <fullName>v8</fullName>
            </value>
            <value>
                <fullName>v9</fullName>
            </value>
            <value>
                <fullName>v10</fullName>
            </value>
            <value>
                <fullName>v11</fullName>
            </value>
            <value>
                <fullName>v12</fullName>
            </value>
            <value>
                <fullName>v13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConnectionSetting__mdt/fields/FirmDomain__c.field-meta.xml
<CustomField>
    <fullName>FirmDomain__c</fullName>
    <inlineHelpText>The firm domain portion of your Addepar API Url.
ie:  Https://mydomain.addepar.com/api</inlineHelpText>
    <label>Firm Domain</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EndpointSetting__mdt/EndpointSetting__mdt.object-meta.xml
<CustomObject>
    <description>Settings for a specific endpoint</description>
    <label>Endpoint Setting</label>
    <pluralLabel>Endpoint Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/EndpointSetting__mdt/fields/ApiVersionVariable__c.field-meta.xml
<CustomField>
    <fullName>ApiVersionVariable__c</fullName>
    <defaultValue>&quot;API_VERSION&quot;</defaultValue>
    <inlineHelpText>The variable in the endpoint URL that represents the API version</inlineHelpText>
    <label>Api Version Variable</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EndpointSetting__mdt/fields/ConnectionSetting__c.field-meta.xml
<CustomField>
    <fullName>ConnectionSetting__c</fullName>
    <inlineHelpText>The connection setting for this endpoint</inlineHelpText>
    <label>Connection Setting</label>
    <referenceTo>ConnectionSetting__mdt</referenceTo>
    <relationshipLabel>Endpoint Settings</relationshipLabel>
    <relationshipName>EndpointSettings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/EndpointSetting__mdt/fields/EndpointURL__c.field-meta.xml
<CustomField>
    <fullName>EndpointURL__c</fullName>
    <defaultValue>&quot;https://FIRM_URL.addepar.com/api/API_VERSION/entity_types&quot;</defaultValue>
    <label>Endpoint URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/EndpointSetting__mdt/fields/FirmUrlVariable__c.field-meta.xml
<CustomField>
    <fullName>FirmUrlVariable__c</fullName>
    <defaultValue>&quot;FIRM_URL&quot;</defaultValue>
    <inlineHelpText>The variable string in the Endpoint URL that represents the firms domain at Addepar.</inlineHelpText>
    <label>Firm Url Variable</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EndpointBuilder.cls
/**
* @author Addepar
* @date 2022
* @group API
* @description Build Endpoint URL from Endpoint and Connection Setting metadata
*/
public with sharing class EndpointBuilder {

    public String endpoint { get; set; }
    
    public EndpointBuilder(EndpointSetting__mdt eps) {
        this.endpoint = getEndpoint(eps);
    }

    private String getEndpoint(EndpointSetting__mdt eps){
        ConnectionSetting__mdt connection = new EndpointSettings().getConnectionSetting(eps.ConnectionSEtting__r.QualifiedAPIName);
        String url = eps.EndpointURL__c;
        url = replaceFirmVariable(eps,url,connection);
        url = replaceApiVersionVariable(eps,url,connection);
        System.debug(LoggingLevel.INFO,'URL After Build: ' + url);
        return url;
    }

    private String replaceFirmVariable(EndpointSetting__mdt eps,String url,ConnectionSetting__mdt connection){
        System.debug(LoggingLevel.INFO,'URL index of firm variable: ' + url.indexOf(eps.FirmUrlVariable__c));
        if(url.indexOf(eps.FirmUrlVariable__c) != -1){
            url = url.replace(eps.FirmUrlVariable__c, connection.FirmDomain__c);
        }
        return url;
    }

    private String replaceApiVersionVariable(EndpointSetting__mdt eps,String url,ConnectionSetting__mdt connection){
        System.debug(LoggingLevel.INFO,'URL index of Version variable: ' + url.indexOf(eps.ApiVersionVariable__c));
        if(url.indexOf(eps.ApiVersionVariable__c) != -1){
            url = url.replace(eps.ApiVersionVariable__c, connection.APIVersion__c);
        }
        return url;
    }
}