force-app/main/default/objects/ConnectionSetting__mdt/ConnectionSetting__mdt.object-meta.xml
<CustomObject>
    <description>Base URLs and other settings for API Connections</description>
    <label>Connection Setting</label>
    <pluralLabel>Connection Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConnectionSetting__mdt/fields/APIKey__c.field-meta.xml
<CustomField>
    <fullName>APIKey__c</fullName>
    <description>The API Key to connect to this endpoint</description>
    <inlineHelpText>The API Key to connect to this endpoint</inlineHelpText>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectionSetting__mdt/fields/APISecret__c.field-meta.xml
<CustomField>
    <fullName>APISecret__c</fullName>
    <inlineHelpText>The API Secret to connect to this endpoint</inlineHelpText>
    <label>API Secret</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConnectionSetting__mdt/fields/APIVersion__c.field-meta.xml
<CustomField>
    <fullName>APIVersion__c</fullName>
    <defaultValue>&quot;NA&quot;</defaultValue>
    <description>The API Version for this endpoint.  Leave as NA if no version is required in callout</description>
    <inlineHelpText>The API Version for this endpoint.  Leave as NA if no version is required in callout</inlineHelpText>
    <label>API Version</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NA</fullName>
                <default>true</default>
                <label>NA</label>
            </value>
            <value>
                <fullName>v1</fullName>
            </value>
            <value>
                <fullName>v2</fullName>
            </value>
            <value>
                <fullName>v3</fullName>
            </value>
            <value>
                <fullName>v4</fullName>
            </value>
            <value>
                <fullName>v5</fullName>
            </value>
            <value>
                <fullName>v6</fullName>
            </value>
            <value>
                <fullName>v7</fullName>
            </value>
            <value>
                <fullName>v8</fullName>
            </value>
            <value>
                <fullName>v9</fullName>
            </value>
            <value>
                <fullName>v10</fullName>
            </value>
            <value>
                <fullName>v11</fullName>
            </value>
            <value>
                <fullName>v12</fullName>
            </value>
            <value>
                <fullName>v13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConnectionSetting__mdt/fields/BaseURL__c.field-meta.xml
<CustomField>
    <fullName>BaseURL__c</fullName>
    <inlineHelpText>The base URL entry point for the API</inlineHelpText>
    <label>Base URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ConnectionSetting__mdt/fields/FirmId__c.field-meta.xml
<CustomField>
    <fullName>FirmId__c</fullName>
    <label>Firm Id</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectionSetting__mdt/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>The password to access this endpoint</description>
    <inlineHelpText>The password to access this endpoint</inlineHelpText>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectionSetting__mdt/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>The username to access this endpoint</description>
    <inlineHelpText>The username to access this endpoint</inlineHelpText>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TradingField__mdt/TradingField__mdt.object-meta.xml
<CustomObject>
    <description>Metadata settings for field attributes from Addepar Trading</description>
    <label>Trading Field</label>
    <pluralLabel>Trading Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/TradingField__mdt/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <inlineHelpText>the API name for the field from Addepar</inlineHelpText>
    <label>API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TradingMap__mdt/TradingMap__mdt.object-meta.xml
<CustomObject>
    <description>User-defined maps of Addepar Trading Objects and Fields to Salesforce SObjects and Fields</description>
    <label>Trading Map</label>
    <pluralLabel>Trading Maps</pluralLabel>
</CustomObject>

force-app/main/default/objects/TradingMap__mdt/fields/RecordTypeDeveloperName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeDeveloperName__c</fullName>
    <defaultValue>&quot;InvestmentAccount&quot;</defaultValue>
    <description>The Record Type Developer Name this mapping applies to for the selected SObject.  Leave blank to apply to all record types or if no record types exist.</description>
    <inlineHelpText>The Record Type Developer Name this mapping applies to for the selected SObject.  Leave blank to apply to all record types or if no record types exist.</inlineHelpText>
    <label>Record Type Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TradingMap__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>The Salesforce SObject this mapping applies to</description>
    <inlineHelpText>The Salesforce SObject this mapping applies to</inlineHelpText>
    <label>SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Trading Maps</relationshipLabel>
    <relationshipName>TradingMaps</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/TradingMap__mdt/fields/SObjectField__c.field-meta.xml
<CustomField>
    <fullName>SObjectField__c</fullName>
    <description>The field on the selected SObject this field assignments points towards.</description>
    <inlineHelpText>The field on the selected SObject this field assignments points towards.</inlineHelpText>
    <label>SObject Field</label>
    <metadataRelationshipControllingField>TradingMap__mdt.SObject__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Trading Maps</relationshipLabel>
    <relationshipName>TradingMaps</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/TradingMap__mdt/fields/SyncDirection__c.field-meta.xml
<CustomField>
    <fullName>SyncDirection__c</fullName>
    <description>The source of truth for this field between Addepar and Salesforce</description>
    <inlineHelpText>The source of truth for this field between Addepar and Salesforce</inlineHelpText>
    <label>Sync Direction</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Addepar to Salesforce</fullName>
                <default>true</default>
                <label>Addepar to Salesforce</label>
            </value>
            <value>
                <fullName>Salesforce to Addepar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TradingMap__mdt/fields/TradingField__c.field-meta.xml
<CustomField>
    <fullName>TradingField__c</fullName>
    <description>The Addepar Trading Entity this mapping applies to</description>
    <inlineHelpText>The Addepar Trading Entity this mapping applies to</inlineHelpText>
    <label>Trading Field</label>
    <referenceTo>TradingField__mdt</referenceTo>
    <relationshipLabel>Trading Maps</relationshipLabel>
    <relationshipName>TradingMaps</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/TradingObject__mdt/TradingObject__mdt.object-meta.xml
<CustomObject>
    <description>Metadata settings for Trading Data objects from Addepar Trading</description>
    <label>Trading Object</label>
    <pluralLabel>Trading Objects</pluralLabel>
</CustomObject>

force-app/main/default/objects/TradingObject__mdt/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <defaultValue>&quot;Account&quot;</defaultValue>
    <inlineHelpText>The Addepar API Name for the Trading Object</inlineHelpText>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TradingSchema__mdt/TradingSchema__mdt.object-meta.xml
<CustomObject>
    <description>Addepar Schema for Trading Entities</description>
    <label>Trading Schema</label>
    <pluralLabel>Trading Schemas</pluralLabel>
</CustomObject>

force-app/main/default/objects/TradingSchema__mdt/fields/DecimalPlaces__c.field-meta.xml
<CustomField>
    <fullName>DecimalPlaces__c</fullName>
    <description>Number of digits to the right of the decimal point</description>
    <inlineHelpText>Number of digits to the right of the decimal point</inlineHelpText>
    <label>Decimal Places</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TradingSchema__mdt/fields/DisplayName__c.field-meta.xml
<CustomField>
    <fullName>DisplayName__c</fullName>
    <inlineHelpText>The display name for this field</inlineHelpText>
    <label>Display Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TradingSchema__mdt/fields/FieldType__c.field-meta.xml
<CustomField>
    <fullName>FieldType__c</fullName>
    <defaultValue>&quot;String&quot;</defaultValue>
    <inlineHelpText>The field type for this schema mapping</inlineHelpText>
    <label>Field Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Boolean</fullName>
                <default>true</default>
                <label>Boolean</label>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>External Id</fullName>
            </value>
            <value>
                <fullName>GUID</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Long Text Area</fullName>
            </value>
            <value>
                <fullName>Multi-Select Picklist</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Rich Text Field</fullName>
            </value>
            <value>
                <fullName>String</fullName>
            </value>
            <value>
                <fullName>Text Area</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TradingSchema__mdt/fields/NumberLength__c.field-meta.xml
<CustomField>
    <fullName>NumberLength__c</fullName>
    <inlineHelpText>Number of digits to the left of the decimal point</inlineHelpText>
    <label>Number Length</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TradingSchema__mdt/fields/PicklistValues__c.field-meta.xml
<CustomField>
    <fullName>PicklistValues__c</fullName>
    <description>A comma-separated list of picklist values for a picklist attribute</description>
    <inlineHelpText>A comma-separated list of picklist values for a picklist attribute</inlineHelpText>
    <label>Picklist Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TradingSchema__mdt/fields/TradingField__c.field-meta.xml
<CustomField>
    <fullName>TradingField__c</fullName>
    <label>Trading Field</label>
    <referenceTo>TradingField__mdt</referenceTo>
    <relationshipLabel>Trading Schemas</relationshipLabel>
    <relationshipName>TradingSchemas</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/TradingSchema__mdt/fields/TradingObject__c.field-meta.xml
<CustomField>
    <fullName>TradingObject__c</fullName>
    <label>Trading Object</label>
    <referenceTo>TradingObject__mdt</referenceTo>
    <relationshipLabel>Trading Schemas</relationshipLabel>
    <relationshipName>TradingSchemas</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/TradingSetting__mdt/TradingSetting__mdt.object-meta.xml
<CustomObject>
    <label>Trading Setting</label>
    <pluralLabel>Trading Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TradingSetting__mdt/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <label>Namespace</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TradingSetting__mdt/fields/TradingEnabledAttribute__c.field-meta.xml
<CustomField>
    <fullName>TradingEnabledAttribute__c</fullName>
    <defaultValue>&quot;_custom_advisorpeaktradingenabled_6701&quot;</defaultValue>
    <label>Trading Enabled Attribute</label>
    <length>55</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MetadataQuery.cls
/**
* @author Kevin Winn
* @date May 17, 2022
* @group Framework
* @description Trading Metadata
*               Contains methods to cache all expected fields from metadata settings to support integration.
*               New fields added to future releases will need to be added to query methods in this class
*/
public with sharing class MetadataQuery {

	/**
    * @description method to cache the Namespace for this package
    * @return Type: String
    */
    public static final String NAMESPACE = StaticResources.ADDEPAR_V3_NAMESPACE;
    
    /**
    * @description method to cache the System Default Qualified API Name for default settings
    *               combine with NAMESPACE string and metadata object name to query default metadata settings 
    * @return Type: String
    */
    public static final String SYSTEM_DEFAULT = 'Default';

    /**
    * @description method to cache the System Test Qualified API Name for test settings
    *               combine with NAMESPACE string and metadata object name to query test metadata settings 
    * @return Type: String
    */
    public static final String SYSTEM_TEST = 'SystemTest';

    /**
    * @description cache all AP field settings
    * @return Type: ConnectionSetting__mdt[]
    */
    public static ConnectionSetting__mdt[] connectionSettings() {
        ConnectionSetting__mdt[] settings = Database.query(connectionSettingsQuery());
        return settings;
    }

    /**
    * @description cache all AP field settings
    * @return Type: TradingField__mdt[]
    */
    public static TradingField__mdt[] tradingFields() {
        TradingField__mdt[] settings = Database.query(tradingFieldsQuery());
        return settings;
    }

    /**
    * @description cache all AP field settings
    * @return Type: TradingMap__mdt[]
    */
    public static TradingMap__mdt[] tradingMaps() {
        TradingMap__mdt[] settings = Database.query(tradingMapQuery());
        return settings;
    }

    /**
    * @description cache all AP field settings
    * @return Type: TradingObject__mdt[]
    */
    public static TradingObject__mdt[] tradingObjects() {
        TradingObject__mdt[] settings = Database.query(tradingObjectsQuery());
        return settings;
    }

    /**
    * @description cache all AP field settings
    * @return Type: TradingSchema__mdt[]
    */
    public static TradingSchema__mdt[] tradingSchemas() {
        TradingSchema__mdt[] settings = Database.query(tradingSchemaQuery());
        return settings;
    }

    /**
    * @author Kevin Winn
    * @return Type: TradingSetting__mdt[]
    */
    public static TradingSetting__mdt tradingSettings() {
        TradingSetting__mdt settings = Database.query(tradingSettingsQuery());
        return settings;
    }

    /**
    * @description prepare query string for standard metadata fields
    * @return Type: String
    * @see https://help.salesforce.com/articleView?id=custommetadatatypes_accessing.htm&amp;type=5
    */
    private static String standardMetaFieldsQuery() {
        return 'Select Id,MasterLabel,QualifiedAPIName,NameSpacePrefix,';
    }

    /**
    * @description prepare query string for Connection Settings metadata object
    * @return Type: String
    */
    private static String connectionSettingsQuery() {
        String base = standardMetaFieldsQuery();
        base += NAMESPACE + 'APIKey__c,'+
        		NAMESPACE + 'APISecret__c,'+
        		NAMESPACE + 'APIVersion__c,'+
        		NAMESPACE + 'BaseURL__c,'+
        		NAMESPACE + 'FirmId__c,'+
        		NAMESPACE + 'Password__c,'+
                NAMESPACE + 'Username__c From ConnectionSetting__mdt';  
        return base;
    }

    /**
    * @description prepare query string for Trading Fields metadata object
    * @return Type: String
    */
    private static String tradingFieldsQuery() {
        String base = standardMetaFieldsQuery();
        base += NAMESPACE + 'APIName__c From TradingField__mdt';  
        return base;
    }

    /**
    * @description prepare query string for Trading Map metadata object
    * @return Type: String
    */
    private static String tradingMapQuery() {
        String base = standardMetaFieldsQuery();
        base += NAMESPACE + 'RecordTypeDeveloperName__c,'+
        		NAMESPACE + 'SyncDirection__c,'+
        		NAMESPACE + 'SObject__c,'+
                NAMESPACE + 'SObject__r.QualifiedAPIName,'+
        		NAMESPACE + 'SObjectField__c,'+
                NAMESPACE + 'SObjectField__r.QualifiedAPIName,'+
                NAMESPACE + 'TradingField__c,'+
                NAMESPACE + 'TradingField__r.QualifiedAPIName From TradingMap__mdt';  
        return base;
    }

    /**
    * @description prepare query string for Trading Object metadata object
    * @return Type: String
    */
    private static String tradingObjectsQuery() {
        String base = standardMetaFieldsQuery();
        base += NAMESPACE + 'APIName__c From TradingObject__mdt';  
        return base;
    }

    /**
    * @description prepare query string for Trading Map metadata object
    * @return Type: String
    */
    private static String tradingSchemaQuery() {
        String base = standardMetaFieldsQuery();
        base += NAMESPACE + 'DecimalPlaces__c,'+
        		NAMESPACE + 'DisplayName__c,'+
        		NAMESPACE + 'FieldType__c,'+
                NAMESPACE + 'NumberLength__c,'+
                NAMESPACE + 'PicklistValues__c,'+
        		NAMESPACE + 'Required__c,'+
                NAMESPACE + 'TradingObject__c,'+
                NAMESPACE + 'TradingObject__r.QualifiedAPIName,'+
                NAMESPACE + 'TradingField__c,'+
                NAMESPACE + 'TradingField__r.QualifiedAPIName From TradingSchema__mdt';  
        return base;
    }

    /**
    * @description prepare query string for Trading Settings metadata object
    * @return Type: String
    */
    private static String tradingSettingsQuery() {
        String base = standardMetaFieldsQuery();
        base += NAMESPACE + 'Namespace__c,'+
                NAMESPACE + 'TradingEnabledAttribute__c From TradingSetting__mdt';  
        return base;
    }    
}